name: Main
on: [push]
env:
  JACOCO_REPORT_REGEX: .*/reports/jacoco/test/jacocoTestReport.xml
jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Run tests
        run: ./gradlew --no-daemon --stacktrace test
      - name: Collect test results
        run: |
          mkdir -p /tmp/codacy
          find . -type f -regex "$JACOCO_REPORT_REGEX" -exec echo {} \; -exec cp --parents {} /tmp/codacy \;
      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: /tmp/codacy
  coverage:
    name: Upload Coverage Report
    needs: build_test
    if: github.ref != 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifect from test results
        uses: actions/download-artifact@v3
        with:
          name: test-results
      - name: Find files
        run: echo "files=$(find . -type f -regex "$JACOCO_REPORT_REGEX" | paste -s -d ',' -)" >> $GITHUB_ENV
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{ env.files }}

